project_id = "hbiqbresabmydufmiphy"

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.avatars]
public = true
file_size_limit = "5MiB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp", "image/gif"]

[storage.buckets.documents]
public = false
file_size_limit = "50MiB"

[storage.buckets.templates]
public = false
file_size_limit = "20MiB"
allowed_mime_types = [
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/pdf",
  "application/msword",
]