/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VendorRouteRouteImport } from './routes/vendor/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSubstitutionsRouteImport } from './routes/_authenticated/substitutions'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNomenclatureRouteImport } from './routes/_authenticated/nomenclature'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as VendorLicenseIndexRouteImport } from './routes/vendor/license/index'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedReferencesIndexRouteImport } from './routes/_authenticated/references/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedCounterpartiesIndexRouteImport } from './routes/_authenticated/counterparties/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as VendorLicenseConsoleRouteImport } from './routes/vendor/license/console'
import { Route as ApiV1TasksRouteImport } from './routes/api/v1/tasks'
import { Route as ApiV1DocumentsRouteImport } from './routes/api/v1/documents'
import { Route as ApiV1ContractsRouteImport } from './routes/api/v1/contracts'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as AuthenticatedWorkflowsIdRouteImport } from './routes/_authenticated/workflows/$id'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates/$id'
import { Route as AuthenticatedReferencesCatalogRouteImport } from './routes/_authenticated/references/$catalog'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects/$id'
import { Route as AuthenticatedKnowledgeNewRouteImport } from './routes/_authenticated/knowledge/new'
import { Route as AuthenticatedKnowledgeManageRouteImport } from './routes/_authenticated/knowledge/manage'
import { Route as AuthenticatedKnowledgeIdRouteImport } from './routes/_authenticated/knowledge/$id'
import { Route as AuthenticatedDocumentsNewRouteImport } from './routes/_authenticated/documents/new'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents/$id'
import { Route as AuthenticatedCounterpartiesIdRouteImport } from './routes/_authenticated/counterparties/$id'
import { Route as AuthenticatedCorrespondenceOutgoingRouteImport } from './routes/_authenticated/correspondence/outgoing'
import { Route as AuthenticatedCorrespondenceIncomingRouteImport } from './routes/_authenticated/correspondence/incoming'
import { Route as AuthenticatedContractsDocumentIdRouteImport } from './routes/_authenticated/contracts/$documentId'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminPositionsRouteImport } from './routes/_authenticated/admin/positions'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminOrganizationRouteImport } from './routes/_authenticated/admin/organization'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin/monitoring'
import { Route as AuthenticatedAdminLicenseRouteImport } from './routes/_authenticated/admin/license'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin/integrations'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin/departments'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin/calendar'
import { Route as AuthenticatedHrTimesheetIndexRouteImport } from './routes/_authenticated/hr/timesheet/index'
import { Route as AuthenticatedHrLeaveIndexRouteImport } from './routes/_authenticated/hr/leave/index'
import { Route as AuthenticatedHrGanttIndexRouteImport } from './routes/_authenticated/hr/gantt/index'
import { Route as AuthenticatedHrDutyIndexRouteImport } from './routes/_authenticated/hr/duty/index'
import { Route as AuthenticatedHrDirectoryIndexRouteImport } from './routes/_authenticated/hr/directory/index'
import { Route as AuthenticatedHrAdminIndexRouteImport } from './routes/_authenticated/hr/admin/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as ApiV1LicenseRevokeRouteImport } from './routes/api/v1/license/revoke'
import { Route as ApiV1LicenseRegisterKeyRouteImport } from './routes/api/v1/license/register-key'
import { Route as ApiV1LicenseHeartbeatRouteImport } from './routes/api/v1/license/heartbeat'
import { Route as ApiV1LicenseHealthRouteImport } from './routes/api/v1/license/health'
import { Route as ApiV1LicenseConnectRouteImport } from './routes/api/v1/license/connect'
import { Route as ApiV1LicenseActivateRouteImport } from './routes/api/v1/license/activate'
import { Route as ApiV1ImportIncomingRouteImport } from './routes/api/v1/import/incoming'
import { Route as ApiV1DocumentsIdRouteImport } from './routes/api/v1/documents.$id'
import { Route as ApiPublicHooksWebhookDispatchRouteImport } from './routes/api/public/hooks/webhook-dispatch'
import { Route as ApiPublicHooksTelegramWebhookRouteImport } from './routes/api/public/hooks/telegram-webhook'
import { Route as ApiPublicHooksTelegramPollRouteImport } from './routes/api/public/hooks/telegram-poll'
import { Route as ApiPublicHooksTelegramDispatchRouteImport } from './routes/api/public/hooks/telegram-dispatch'
import { Route as ApiPublicHooksSlaTickRouteImport } from './routes/api/public/hooks/sla-tick'
import { Route as ApiPublicHooksRetentionTickRouteImport } from './routes/api/public/hooks/retention-tick'
import { Route as ApiPublicHooksOfficeCallbackRouteImport } from './routes/api/public/hooks/office-callback'
import { Route as ApiPublicHooksLicenseSyncRouteImport } from './routes/api/public/hooks/license-sync'
import { Route as ApiPublicHooksEmailDispatchRouteImport } from './routes/api/public/hooks/email-dispatch'
import { Route as AuthenticatedKnowledgeIdEditRouteImport } from './routes/_authenticated/knowledge/$id.edit'
import { Route as AuthenticatedHrLeaveScheduleRouteImport } from './routes/_authenticated/hr/leave/schedule'
import { Route as AuthenticatedHrLeaveApprovalsRouteImport } from './routes/_authenticated/hr/leave/approvals'
import { Route as AuthenticatedHrGanttIdRouteImport } from './routes/_authenticated/hr/gantt/$id'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin/users/$id'
import { Route as ApiV1TasksIdCompleteRouteImport } from './routes/api/v1/tasks.$id.complete'
import { Route as ApiV1DocumentsIdVersionsRouteImport } from './routes/api/v1/documents.$id.versions'
import { Route as ApiV1DocumentsIdStatusRouteImport } from './routes/api/v1/documents.$id.status'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRouteRoute = VendorRouteRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubstitutionsRoute =
  AuthenticatedSubstitutionsRouteImport.update({
    id: '/substitutions',
    path: '/substitutions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNomenclatureRoute =
  AuthenticatedNomenclatureRouteImport.update({
    id: '/nomenclature',
    path: '/nomenclature',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VendorLicenseIndexRoute = VendorLicenseIndexRouteImport.update({
  id: '/license/',
  path: '/license/',
  getParentRoute: () => VendorRouteRoute,
} as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferencesIndexRoute =
  AuthenticatedReferencesIndexRouteImport.update({
    id: '/references/',
    path: '/references/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCounterpartiesIndexRoute =
  AuthenticatedCounterpartiesIndexRouteImport.update({
    id: '/counterparties/',
    path: '/counterparties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const VendorLicenseConsoleRoute = VendorLicenseConsoleRouteImport.update({
  id: '/license/console',
  path: '/license/console',
  getParentRoute: () => VendorRouteRoute,
} as any)
const ApiV1TasksRoute = ApiV1TasksRouteImport.update({
  id: '/api/v1/tasks',
  path: '/api/v1/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DocumentsRoute = ApiV1DocumentsRouteImport.update({
  id: '/api/v1/documents',
  path: '/api/v1/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContractsRoute = ApiV1ContractsRouteImport.update({
  id: '/api/v1/contracts',
  path: '/api/v1/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiHealthRoute,
} as any)
const AuthenticatedWorkflowsIdRoute =
  AuthenticatedWorkflowsIdRouteImport.update({
    id: '/workflows/$id',
    path: '/workflows/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferencesCatalogRoute =
  AuthenticatedReferencesCatalogRouteImport.update({
    id: '/references/$catalog',
    path: '/references/$catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeNewRoute =
  AuthenticatedKnowledgeNewRouteImport.update({
    id: '/knowledge/new',
    path: '/knowledge/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeManageRoute =
  AuthenticatedKnowledgeManageRouteImport.update({
    id: '/knowledge/manage',
    path: '/knowledge/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeIdRoute =
  AuthenticatedKnowledgeIdRouteImport.update({
    id: '/knowledge/$id',
    path: '/knowledge/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsNewRoute =
  AuthenticatedDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCounterpartiesIdRoute =
  AuthenticatedCounterpartiesIdRouteImport.update({
    id: '/counterparties/$id',
    path: '/counterparties/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorrespondenceOutgoingRoute =
  AuthenticatedCorrespondenceOutgoingRouteImport.update({
    id: '/correspondence/outgoing',
    path: '/correspondence/outgoing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCorrespondenceIncomingRoute =
  AuthenticatedCorrespondenceIncomingRouteImport.update({
    id: '/correspondence/incoming',
    path: '/correspondence/incoming',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsDocumentIdRoute =
  AuthenticatedContractsDocumentIdRouteImport.update({
    id: '/contracts/$documentId',
    path: '/contracts/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPositionsRoute =
  AuthenticatedAdminPositionsRouteImport.update({
    id: '/admin/positions',
    path: '/admin/positions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationRoute =
  AuthenticatedAdminOrganizationRouteImport.update({
    id: '/admin/organization',
    path: '/admin/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/admin/monitoring',
    path: '/admin/monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLicenseRoute =
  AuthenticatedAdminLicenseRouteImport.update({
    id: '/admin/license',
    path: '/admin/license',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/admin/calendar',
    path: '/admin/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrTimesheetIndexRoute =
  AuthenticatedHrTimesheetIndexRouteImport.update({
    id: '/hr/timesheet/',
    path: '/hr/timesheet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrLeaveIndexRoute =
  AuthenticatedHrLeaveIndexRouteImport.update({
    id: '/hr/leave/',
    path: '/hr/leave/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrGanttIndexRoute =
  AuthenticatedHrGanttIndexRouteImport.update({
    id: '/hr/gantt/',
    path: '/hr/gantt/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrDutyIndexRoute =
  AuthenticatedHrDutyIndexRouteImport.update({
    id: '/hr/duty/',
    path: '/hr/duty/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrDirectoryIndexRoute =
  AuthenticatedHrDirectoryIndexRouteImport.update({
    id: '/hr/directory/',
    path: '/hr/directory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAdminIndexRoute =
  AuthenticatedHrAdminIndexRouteImport.update({
    id: '/hr/admin/',
    path: '/hr/admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiV1LicenseRevokeRoute = ApiV1LicenseRevokeRouteImport.update({
  id: '/api/v1/license/revoke',
  path: '/api/v1/license/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LicenseRegisterKeyRoute = ApiV1LicenseRegisterKeyRouteImport.update({
  id: '/api/v1/license/register-key',
  path: '/api/v1/license/register-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LicenseHeartbeatRoute = ApiV1LicenseHeartbeatRouteImport.update({
  id: '/api/v1/license/heartbeat',
  path: '/api/v1/license/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LicenseHealthRoute = ApiV1LicenseHealthRouteImport.update({
  id: '/api/v1/license/health',
  path: '/api/v1/license/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LicenseConnectRoute = ApiV1LicenseConnectRouteImport.update({
  id: '/api/v1/license/connect',
  path: '/api/v1/license/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LicenseActivateRoute = ApiV1LicenseActivateRouteImport.update({
  id: '/api/v1/license/activate',
  path: '/api/v1/license/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ImportIncomingRoute = ApiV1ImportIncomingRouteImport.update({
  id: '/api/v1/import/incoming',
  path: '/api/v1/import/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DocumentsIdRoute = ApiV1DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1DocumentsRoute,
} as any)
const ApiPublicHooksWebhookDispatchRoute =
  ApiPublicHooksWebhookDispatchRouteImport.update({
    id: '/api/public/hooks/webhook-dispatch',
    path: '/api/public/hooks/webhook-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramWebhookRoute =
  ApiPublicHooksTelegramWebhookRouteImport.update({
    id: '/api/public/hooks/telegram-webhook',
    path: '/api/public/hooks/telegram-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramPollRoute =
  ApiPublicHooksTelegramPollRouteImport.update({
    id: '/api/public/hooks/telegram-poll',
    path: '/api/public/hooks/telegram-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTelegramDispatchRoute =
  ApiPublicHooksTelegramDispatchRouteImport.update({
    id: '/api/public/hooks/telegram-dispatch',
    path: '/api/public/hooks/telegram-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSlaTickRoute = ApiPublicHooksSlaTickRouteImport.update({
  id: '/api/public/hooks/sla-tick',
  path: '/api/public/hooks/sla-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRetentionTickRoute =
  ApiPublicHooksRetentionTickRouteImport.update({
    id: '/api/public/hooks/retention-tick',
    path: '/api/public/hooks/retention-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOfficeCallbackRoute =
  ApiPublicHooksOfficeCallbackRouteImport.update({
    id: '/api/public/hooks/office-callback',
    path: '/api/public/hooks/office-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLicenseSyncRoute =
  ApiPublicHooksLicenseSyncRouteImport.update({
    id: '/api/public/hooks/license-sync',
    path: '/api/public/hooks/license-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailDispatchRoute =
  ApiPublicHooksEmailDispatchRouteImport.update({
    id: '/api/public/hooks/email-dispatch',
    path: '/api/public/hooks/email-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKnowledgeIdEditRoute =
  AuthenticatedKnowledgeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedKnowledgeIdRoute,
  } as any)
const AuthenticatedHrLeaveScheduleRoute =
  AuthenticatedHrLeaveScheduleRouteImport.update({
    id: '/hr/leave/schedule',
    path: '/hr/leave/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrLeaveApprovalsRoute =
  AuthenticatedHrLeaveApprovalsRouteImport.update({
    id: '/hr/leave/approvals',
    path: '/hr/leave/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrGanttIdRoute = AuthenticatedHrGanttIdRouteImport.update({
  id: '/hr/gantt/$id',
  path: '/hr/gantt/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/admin/users/$id',
    path: '/admin/users/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiV1TasksIdCompleteRoute = ApiV1TasksIdCompleteRouteImport.update({
  id: '/$id/complete',
  path: '/$id/complete',
  getParentRoute: () => ApiV1TasksRoute,
} as any)
const ApiV1DocumentsIdVersionsRoute =
  ApiV1DocumentsIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => ApiV1DocumentsIdRoute,
  } as any)
const ApiV1DocumentsIdStatusRoute = ApiV1DocumentsIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiV1DocumentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vendor': typeof VendorRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/nomenclature': typeof AuthenticatedNomenclatureRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/substitutions': typeof AuthenticatedSubstitutionsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/license': typeof AuthenticatedAdminLicenseRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/contracts/$documentId': typeof AuthenticatedContractsDocumentIdRoute
  '/correspondence/incoming': typeof AuthenticatedCorrespondenceIncomingRoute
  '/correspondence/outgoing': typeof AuthenticatedCorrespondenceOutgoingRoute
  '/counterparties/$id': typeof AuthenticatedCounterpartiesIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRouteWithChildren
  '/knowledge/manage': typeof AuthenticatedKnowledgeManageRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/references/$catalog': typeof AuthenticatedReferencesCatalogRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/v1/contracts': typeof ApiV1ContractsRoute
  '/api/v1/documents': typeof ApiV1DocumentsRouteWithChildren
  '/api/v1/tasks': typeof ApiV1TasksRouteWithChildren
  '/vendor/license/console': typeof VendorLicenseConsoleRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/counterparties/': typeof AuthenticatedCounterpartiesIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/references/': typeof AuthenticatedReferencesIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/vendor/license/': typeof VendorLicenseIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/hr/gantt/$id': typeof AuthenticatedHrGanttIdRoute
  '/hr/leave/approvals': typeof AuthenticatedHrLeaveApprovalsRoute
  '/hr/leave/schedule': typeof AuthenticatedHrLeaveScheduleRoute
  '/knowledge/$id/edit': typeof AuthenticatedKnowledgeIdEditRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/license-sync': typeof ApiPublicHooksLicenseSyncRoute
  '/api/public/hooks/office-callback': typeof ApiPublicHooksOfficeCallbackRoute
  '/api/public/hooks/retention-tick': typeof ApiPublicHooksRetentionTickRoute
  '/api/public/hooks/sla-tick': typeof ApiPublicHooksSlaTickRoute
  '/api/public/hooks/telegram-dispatch': typeof ApiPublicHooksTelegramDispatchRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
  '/api/public/hooks/webhook-dispatch': typeof ApiPublicHooksWebhookDispatchRoute
  '/api/v1/documents/$id': typeof ApiV1DocumentsIdRouteWithChildren
  '/api/v1/import/incoming': typeof ApiV1ImportIncomingRoute
  '/api/v1/license/activate': typeof ApiV1LicenseActivateRoute
  '/api/v1/license/connect': typeof ApiV1LicenseConnectRoute
  '/api/v1/license/health': typeof ApiV1LicenseHealthRoute
  '/api/v1/license/heartbeat': typeof ApiV1LicenseHeartbeatRoute
  '/api/v1/license/register-key': typeof ApiV1LicenseRegisterKeyRoute
  '/api/v1/license/revoke': typeof ApiV1LicenseRevokeRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/hr/admin/': typeof AuthenticatedHrAdminIndexRoute
  '/hr/directory/': typeof AuthenticatedHrDirectoryIndexRoute
  '/hr/duty/': typeof AuthenticatedHrDutyIndexRoute
  '/hr/gantt/': typeof AuthenticatedHrGanttIndexRoute
  '/hr/leave/': typeof AuthenticatedHrLeaveIndexRoute
  '/hr/timesheet/': typeof AuthenticatedHrTimesheetIndexRoute
  '/api/v1/documents/$id/status': typeof ApiV1DocumentsIdStatusRoute
  '/api/v1/documents/$id/versions': typeof ApiV1DocumentsIdVersionsRoute
  '/api/v1/tasks/$id/complete': typeof ApiV1TasksIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vendor': typeof VendorRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/nomenclature': typeof AuthenticatedNomenclatureRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/substitutions': typeof AuthenticatedSubstitutionsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/license': typeof AuthenticatedAdminLicenseRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/contracts/$documentId': typeof AuthenticatedContractsDocumentIdRoute
  '/correspondence/incoming': typeof AuthenticatedCorrespondenceIncomingRoute
  '/correspondence/outgoing': typeof AuthenticatedCorrespondenceOutgoingRoute
  '/counterparties/$id': typeof AuthenticatedCounterpartiesIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/knowledge/$id': typeof AuthenticatedKnowledgeIdRouteWithChildren
  '/knowledge/manage': typeof AuthenticatedKnowledgeManageRoute
  '/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/references/$catalog': typeof AuthenticatedReferencesCatalogRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/v1/contracts': typeof ApiV1ContractsRoute
  '/api/v1/documents': typeof ApiV1DocumentsRouteWithChildren
  '/api/v1/tasks': typeof ApiV1TasksRouteWithChildren
  '/vendor/license/console': typeof VendorLicenseConsoleRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/counterparties': typeof AuthenticatedCounterpartiesIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/references': typeof AuthenticatedReferencesIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/vendor/license': typeof VendorLicenseIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/hr/gantt/$id': typeof AuthenticatedHrGanttIdRoute
  '/hr/leave/approvals': typeof AuthenticatedHrLeaveApprovalsRoute
  '/hr/leave/schedule': typeof AuthenticatedHrLeaveScheduleRoute
  '/knowledge/$id/edit': typeof AuthenticatedKnowledgeIdEditRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/license-sync': typeof ApiPublicHooksLicenseSyncRoute
  '/api/public/hooks/office-callback': typeof ApiPublicHooksOfficeCallbackRoute
  '/api/public/hooks/retention-tick': typeof ApiPublicHooksRetentionTickRoute
  '/api/public/hooks/sla-tick': typeof ApiPublicHooksSlaTickRoute
  '/api/public/hooks/telegram-dispatch': typeof ApiPublicHooksTelegramDispatchRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
  '/api/public/hooks/webhook-dispatch': typeof ApiPublicHooksWebhookDispatchRoute
  '/api/v1/documents/$id': typeof ApiV1DocumentsIdRouteWithChildren
  '/api/v1/import/incoming': typeof ApiV1ImportIncomingRoute
  '/api/v1/license/activate': typeof ApiV1LicenseActivateRoute
  '/api/v1/license/connect': typeof ApiV1LicenseConnectRoute
  '/api/v1/license/health': typeof ApiV1LicenseHealthRoute
  '/api/v1/license/heartbeat': typeof ApiV1LicenseHeartbeatRoute
  '/api/v1/license/register-key': typeof ApiV1LicenseRegisterKeyRoute
  '/api/v1/license/revoke': typeof ApiV1LicenseRevokeRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/hr/admin': typeof AuthenticatedHrAdminIndexRoute
  '/hr/directory': typeof AuthenticatedHrDirectoryIndexRoute
  '/hr/duty': typeof AuthenticatedHrDutyIndexRoute
  '/hr/gantt': typeof AuthenticatedHrGanttIndexRoute
  '/hr/leave': typeof AuthenticatedHrLeaveIndexRoute
  '/hr/timesheet': typeof AuthenticatedHrTimesheetIndexRoute
  '/api/v1/documents/$id/status': typeof ApiV1DocumentsIdStatusRoute
  '/api/v1/documents/$id/versions': typeof ApiV1DocumentsIdVersionsRoute
  '/api/v1/tasks/$id/complete': typeof ApiV1TasksIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/vendor': typeof VendorRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/nomenclature': typeof AuthenticatedNomenclatureRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/substitutions': typeof AuthenticatedSubstitutionsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/license': typeof AuthenticatedAdminLicenseRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/admin/organization': typeof AuthenticatedAdminOrganizationRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/positions': typeof AuthenticatedAdminPositionsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/contracts/$documentId': typeof AuthenticatedContractsDocumentIdRoute
  '/_authenticated/correspondence/incoming': typeof AuthenticatedCorrespondenceIncomingRoute
  '/_authenticated/correspondence/outgoing': typeof AuthenticatedCorrespondenceOutgoingRoute
  '/_authenticated/counterparties/$id': typeof AuthenticatedCounterpartiesIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/_authenticated/knowledge/$id': typeof AuthenticatedKnowledgeIdRouteWithChildren
  '/_authenticated/knowledge/manage': typeof AuthenticatedKnowledgeManageRoute
  '/_authenticated/knowledge/new': typeof AuthenticatedKnowledgeNewRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/references/$catalog': typeof AuthenticatedReferencesCatalogRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/_authenticated/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/v1/contracts': typeof ApiV1ContractsRoute
  '/api/v1/documents': typeof ApiV1DocumentsRouteWithChildren
  '/api/v1/tasks': typeof ApiV1TasksRouteWithChildren
  '/vendor/license/console': typeof VendorLicenseConsoleRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/counterparties/': typeof AuthenticatedCounterpartiesIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/references/': typeof AuthenticatedReferencesIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/vendor/license/': typeof VendorLicenseIndexRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/_authenticated/hr/gantt/$id': typeof AuthenticatedHrGanttIdRoute
  '/_authenticated/hr/leave/approvals': typeof AuthenticatedHrLeaveApprovalsRoute
  '/_authenticated/hr/leave/schedule': typeof AuthenticatedHrLeaveScheduleRoute
  '/_authenticated/knowledge/$id/edit': typeof AuthenticatedKnowledgeIdEditRoute
  '/api/public/hooks/email-dispatch': typeof ApiPublicHooksEmailDispatchRoute
  '/api/public/hooks/license-sync': typeof ApiPublicHooksLicenseSyncRoute
  '/api/public/hooks/office-callback': typeof ApiPublicHooksOfficeCallbackRoute
  '/api/public/hooks/retention-tick': typeof ApiPublicHooksRetentionTickRoute
  '/api/public/hooks/sla-tick': typeof ApiPublicHooksSlaTickRoute
  '/api/public/hooks/telegram-dispatch': typeof ApiPublicHooksTelegramDispatchRoute
  '/api/public/hooks/telegram-poll': typeof ApiPublicHooksTelegramPollRoute
  '/api/public/hooks/telegram-webhook': typeof ApiPublicHooksTelegramWebhookRoute
  '/api/public/hooks/webhook-dispatch': typeof ApiPublicHooksWebhookDispatchRoute
  '/api/v1/documents/$id': typeof ApiV1DocumentsIdRouteWithChildren
  '/api/v1/import/incoming': typeof ApiV1ImportIncomingRoute
  '/api/v1/license/activate': typeof ApiV1LicenseActivateRoute
  '/api/v1/license/connect': typeof ApiV1LicenseConnectRoute
  '/api/v1/license/health': typeof ApiV1LicenseHealthRoute
  '/api/v1/license/heartbeat': typeof ApiV1LicenseHeartbeatRoute
  '/api/v1/license/register-key': typeof ApiV1LicenseRegisterKeyRoute
  '/api/v1/license/revoke': typeof ApiV1LicenseRevokeRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/hr/admin/': typeof AuthenticatedHrAdminIndexRoute
  '/_authenticated/hr/directory/': typeof AuthenticatedHrDirectoryIndexRoute
  '/_authenticated/hr/duty/': typeof AuthenticatedHrDutyIndexRoute
  '/_authenticated/hr/gantt/': typeof AuthenticatedHrGanttIndexRoute
  '/_authenticated/hr/leave/': typeof AuthenticatedHrLeaveIndexRoute
  '/_authenticated/hr/timesheet/': typeof AuthenticatedHrTimesheetIndexRoute
  '/api/v1/documents/$id/status': typeof ApiV1DocumentsIdStatusRoute
  '/api/v1/documents/$id/versions': typeof ApiV1DocumentsIdVersionsRoute
  '/api/v1/tasks/$id/complete': typeof ApiV1TasksIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vendor'
    | '/auth'
    | '/approvals'
    | '/archive'
    | '/audit'
    | '/dashboard'
    | '/help'
    | '/nomenclature'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/search'
    | '/substitutions'
    | '/tasks'
    | '/api/health'
    | '/admin/calendar'
    | '/admin/departments'
    | '/admin/integrations'
    | '/admin/license'
    | '/admin/monitoring'
    | '/admin/organization'
    | '/admin/permissions'
    | '/admin/positions'
    | '/admin/roles'
    | '/admin/settings'
    | '/contracts/$documentId'
    | '/correspondence/incoming'
    | '/correspondence/outgoing'
    | '/counterparties/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/knowledge/$id'
    | '/knowledge/manage'
    | '/knowledge/new'
    | '/projects/$id'
    | '/references/$catalog'
    | '/templates/$id'
    | '/workflows/$id'
    | '/api/health/live'
    | '/api/v1/contracts'
    | '/api/v1/documents'
    | '/api/v1/tasks'
    | '/vendor/license/console'
    | '/contracts/'
    | '/counterparties/'
    | '/documents/'
    | '/knowledge/'
    | '/projects/'
    | '/references/'
    | '/templates/'
    | '/workflows/'
    | '/vendor/license/'
    | '/admin/users/$id'
    | '/hr/gantt/$id'
    | '/hr/leave/approvals'
    | '/hr/leave/schedule'
    | '/knowledge/$id/edit'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/license-sync'
    | '/api/public/hooks/office-callback'
    | '/api/public/hooks/retention-tick'
    | '/api/public/hooks/sla-tick'
    | '/api/public/hooks/telegram-dispatch'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/hooks/telegram-webhook'
    | '/api/public/hooks/webhook-dispatch'
    | '/api/v1/documents/$id'
    | '/api/v1/import/incoming'
    | '/api/v1/license/activate'
    | '/api/v1/license/connect'
    | '/api/v1/license/health'
    | '/api/v1/license/heartbeat'
    | '/api/v1/license/register-key'
    | '/api/v1/license/revoke'
    | '/admin/users/'
    | '/hr/admin/'
    | '/hr/directory/'
    | '/hr/duty/'
    | '/hr/gantt/'
    | '/hr/leave/'
    | '/hr/timesheet/'
    | '/api/v1/documents/$id/status'
    | '/api/v1/documents/$id/versions'
    | '/api/v1/tasks/$id/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vendor'
    | '/auth'
    | '/approvals'
    | '/archive'
    | '/audit'
    | '/dashboard'
    | '/help'
    | '/nomenclature'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/search'
    | '/substitutions'
    | '/tasks'
    | '/api/health'
    | '/admin/calendar'
    | '/admin/departments'
    | '/admin/integrations'
    | '/admin/license'
    | '/admin/monitoring'
    | '/admin/organization'
    | '/admin/permissions'
    | '/admin/positions'
    | '/admin/roles'
    | '/admin/settings'
    | '/contracts/$documentId'
    | '/correspondence/incoming'
    | '/correspondence/outgoing'
    | '/counterparties/$id'
    | '/documents/$id'
    | '/documents/new'
    | '/knowledge/$id'
    | '/knowledge/manage'
    | '/knowledge/new'
    | '/projects/$id'
    | '/references/$catalog'
    | '/templates/$id'
    | '/workflows/$id'
    | '/api/health/live'
    | '/api/v1/contracts'
    | '/api/v1/documents'
    | '/api/v1/tasks'
    | '/vendor/license/console'
    | '/contracts'
    | '/counterparties'
    | '/documents'
    | '/knowledge'
    | '/projects'
    | '/references'
    | '/templates'
    | '/workflows'
    | '/vendor/license'
    | '/admin/users/$id'
    | '/hr/gantt/$id'
    | '/hr/leave/approvals'
    | '/hr/leave/schedule'
    | '/knowledge/$id/edit'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/license-sync'
    | '/api/public/hooks/office-callback'
    | '/api/public/hooks/retention-tick'
    | '/api/public/hooks/sla-tick'
    | '/api/public/hooks/telegram-dispatch'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/hooks/telegram-webhook'
    | '/api/public/hooks/webhook-dispatch'
    | '/api/v1/documents/$id'
    | '/api/v1/import/incoming'
    | '/api/v1/license/activate'
    | '/api/v1/license/connect'
    | '/api/v1/license/health'
    | '/api/v1/license/heartbeat'
    | '/api/v1/license/register-key'
    | '/api/v1/license/revoke'
    | '/admin/users'
    | '/hr/admin'
    | '/hr/directory'
    | '/hr/duty'
    | '/hr/gantt'
    | '/hr/leave'
    | '/hr/timesheet'
    | '/api/v1/documents/$id/status'
    | '/api/v1/documents/$id/versions'
    | '/api/v1/tasks/$id/complete'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/vendor'
    | '/auth'
    | '/_authenticated/approvals'
    | '/_authenticated/archive'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/nomenclature'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/substitutions'
    | '/_authenticated/tasks'
    | '/api/health'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/license'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/admin/organization'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/positions'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/contracts/$documentId'
    | '/_authenticated/correspondence/incoming'
    | '/_authenticated/correspondence/outgoing'
    | '/_authenticated/counterparties/$id'
    | '/_authenticated/documents/$id'
    | '/_authenticated/documents/new'
    | '/_authenticated/knowledge/$id'
    | '/_authenticated/knowledge/manage'
    | '/_authenticated/knowledge/new'
    | '/_authenticated/projects/$id'
    | '/_authenticated/references/$catalog'
    | '/_authenticated/templates/$id'
    | '/_authenticated/workflows/$id'
    | '/api/health/live'
    | '/api/v1/contracts'
    | '/api/v1/documents'
    | '/api/v1/tasks'
    | '/vendor/license/console'
    | '/_authenticated/contracts/'
    | '/_authenticated/counterparties/'
    | '/_authenticated/documents/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/projects/'
    | '/_authenticated/references/'
    | '/_authenticated/templates/'
    | '/_authenticated/workflows/'
    | '/vendor/license/'
    | '/_authenticated/admin/users/$id'
    | '/_authenticated/hr/gantt/$id'
    | '/_authenticated/hr/leave/approvals'
    | '/_authenticated/hr/leave/schedule'
    | '/_authenticated/knowledge/$id/edit'
    | '/api/public/hooks/email-dispatch'
    | '/api/public/hooks/license-sync'
    | '/api/public/hooks/office-callback'
    | '/api/public/hooks/retention-tick'
    | '/api/public/hooks/sla-tick'
    | '/api/public/hooks/telegram-dispatch'
    | '/api/public/hooks/telegram-poll'
    | '/api/public/hooks/telegram-webhook'
    | '/api/public/hooks/webhook-dispatch'
    | '/api/v1/documents/$id'
    | '/api/v1/import/incoming'
    | '/api/v1/license/activate'
    | '/api/v1/license/connect'
    | '/api/v1/license/health'
    | '/api/v1/license/heartbeat'
    | '/api/v1/license/register-key'
    | '/api/v1/license/revoke'
    | '/_authenticated/admin/users/'
    | '/_authenticated/hr/admin/'
    | '/_authenticated/hr/directory/'
    | '/_authenticated/hr/duty/'
    | '/_authenticated/hr/gantt/'
    | '/_authenticated/hr/leave/'
    | '/_authenticated/hr/timesheet/'
    | '/api/v1/documents/$id/status'
    | '/api/v1/documents/$id/versions'
    | '/api/v1/tasks/$id/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  VendorRouteRoute: typeof VendorRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiV1ContractsRoute: typeof ApiV1ContractsRoute
  ApiV1DocumentsRoute: typeof ApiV1DocumentsRouteWithChildren
  ApiV1TasksRoute: typeof ApiV1TasksRouteWithChildren
  ApiPublicHooksEmailDispatchRoute: typeof ApiPublicHooksEmailDispatchRoute
  ApiPublicHooksLicenseSyncRoute: typeof ApiPublicHooksLicenseSyncRoute
  ApiPublicHooksOfficeCallbackRoute: typeof ApiPublicHooksOfficeCallbackRoute
  ApiPublicHooksRetentionTickRoute: typeof ApiPublicHooksRetentionTickRoute
  ApiPublicHooksSlaTickRoute: typeof ApiPublicHooksSlaTickRoute
  ApiPublicHooksTelegramDispatchRoute: typeof ApiPublicHooksTelegramDispatchRoute
  ApiPublicHooksTelegramPollRoute: typeof ApiPublicHooksTelegramPollRoute
  ApiPublicHooksTelegramWebhookRoute: typeof ApiPublicHooksTelegramWebhookRoute
  ApiPublicHooksWebhookDispatchRoute: typeof ApiPublicHooksWebhookDispatchRoute
  ApiV1ImportIncomingRoute: typeof ApiV1ImportIncomingRoute
  ApiV1LicenseActivateRoute: typeof ApiV1LicenseActivateRoute
  ApiV1LicenseConnectRoute: typeof ApiV1LicenseConnectRoute
  ApiV1LicenseHealthRoute: typeof ApiV1LicenseHealthRoute
  ApiV1LicenseHeartbeatRoute: typeof ApiV1LicenseHeartbeatRoute
  ApiV1LicenseRegisterKeyRoute: typeof ApiV1LicenseRegisterKeyRoute
  ApiV1LicenseRevokeRoute: typeof ApiV1LicenseRevokeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/substitutions': {
      id: '/_authenticated/substitutions'
      path: '/substitutions'
      fullPath: '/substitutions'
      preLoaderRoute: typeof AuthenticatedSubstitutionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nomenclature': {
      id: '/_authenticated/nomenclature'
      path: '/nomenclature'
      fullPath: '/nomenclature'
      preLoaderRoute: typeof AuthenticatedNomenclatureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/vendor/license/': {
      id: '/vendor/license/'
      path: '/license'
      fullPath: '/vendor/license/'
      preLoaderRoute: typeof VendorLicenseIndexRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/references/': {
      id: '/_authenticated/references/'
      path: '/references'
      fullPath: '/references/'
      preLoaderRoute: typeof AuthenticatedReferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counterparties/': {
      id: '/_authenticated/counterparties/'
      path: '/counterparties'
      fullPath: '/counterparties/'
      preLoaderRoute: typeof AuthenticatedCounterpartiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/vendor/license/console': {
      id: '/vendor/license/console'
      path: '/license/console'
      fullPath: '/vendor/license/console'
      preLoaderRoute: typeof VendorLicenseConsoleRouteImport
      parentRoute: typeof VendorRouteRoute
    }
    '/api/v1/tasks': {
      id: '/api/v1/tasks'
      path: '/api/v1/tasks'
      fullPath: '/api/v1/tasks'
      preLoaderRoute: typeof ApiV1TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/documents': {
      id: '/api/v1/documents'
      path: '/api/v1/documents'
      fullPath: '/api/v1/documents'
      preLoaderRoute: typeof ApiV1DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contracts': {
      id: '/api/v1/contracts'
      path: '/api/v1/contracts'
      fullPath: '/api/v1/contracts'
      preLoaderRoute: typeof ApiV1ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/_authenticated/workflows/$id': {
      id: '/_authenticated/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AuthenticatedWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/references/$catalog': {
      id: '/_authenticated/references/$catalog'
      path: '/references/$catalog'
      fullPath: '/references/$catalog'
      preLoaderRoute: typeof AuthenticatedReferencesCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/new': {
      id: '/_authenticated/knowledge/new'
      path: '/knowledge/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof AuthenticatedKnowledgeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/manage': {
      id: '/_authenticated/knowledge/manage'
      path: '/knowledge/manage'
      fullPath: '/knowledge/manage'
      preLoaderRoute: typeof AuthenticatedKnowledgeManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/$id': {
      id: '/_authenticated/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof AuthenticatedKnowledgeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/new': {
      id: '/_authenticated/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthenticatedDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/counterparties/$id': {
      id: '/_authenticated/counterparties/$id'
      path: '/counterparties/$id'
      fullPath: '/counterparties/$id'
      preLoaderRoute: typeof AuthenticatedCounterpartiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/correspondence/outgoing': {
      id: '/_authenticated/correspondence/outgoing'
      path: '/correspondence/outgoing'
      fullPath: '/correspondence/outgoing'
      preLoaderRoute: typeof AuthenticatedCorrespondenceOutgoingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/correspondence/incoming': {
      id: '/_authenticated/correspondence/incoming'
      path: '/correspondence/incoming'
      fullPath: '/correspondence/incoming'
      preLoaderRoute: typeof AuthenticatedCorrespondenceIncomingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$documentId': {
      id: '/_authenticated/contracts/$documentId'
      path: '/contracts/$documentId'
      fullPath: '/contracts/$documentId'
      preLoaderRoute: typeof AuthenticatedContractsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/positions': {
      id: '/_authenticated/admin/positions'
      path: '/admin/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AuthenticatedAdminPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organization': {
      id: '/_authenticated/admin/organization'
      path: '/admin/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/license': {
      id: '/_authenticated/admin/license'
      path: '/admin/license'
      fullPath: '/admin/license'
      preLoaderRoute: typeof AuthenticatedAdminLicenseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/admin/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/timesheet/': {
      id: '/_authenticated/hr/timesheet/'
      path: '/hr/timesheet'
      fullPath: '/hr/timesheet/'
      preLoaderRoute: typeof AuthenticatedHrTimesheetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/leave/': {
      id: '/_authenticated/hr/leave/'
      path: '/hr/leave'
      fullPath: '/hr/leave/'
      preLoaderRoute: typeof AuthenticatedHrLeaveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/gantt/': {
      id: '/_authenticated/hr/gantt/'
      path: '/hr/gantt'
      fullPath: '/hr/gantt/'
      preLoaderRoute: typeof AuthenticatedHrGanttIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/duty/': {
      id: '/_authenticated/hr/duty/'
      path: '/hr/duty'
      fullPath: '/hr/duty/'
      preLoaderRoute: typeof AuthenticatedHrDutyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/directory/': {
      id: '/_authenticated/hr/directory/'
      path: '/hr/directory'
      fullPath: '/hr/directory/'
      preLoaderRoute: typeof AuthenticatedHrDirectoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/admin/': {
      id: '/_authenticated/hr/admin/'
      path: '/hr/admin'
      fullPath: '/hr/admin/'
      preLoaderRoute: typeof AuthenticatedHrAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/v1/license/revoke': {
      id: '/api/v1/license/revoke'
      path: '/api/v1/license/revoke'
      fullPath: '/api/v1/license/revoke'
      preLoaderRoute: typeof ApiV1LicenseRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/license/register-key': {
      id: '/api/v1/license/register-key'
      path: '/api/v1/license/register-key'
      fullPath: '/api/v1/license/register-key'
      preLoaderRoute: typeof ApiV1LicenseRegisterKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/license/heartbeat': {
      id: '/api/v1/license/heartbeat'
      path: '/api/v1/license/heartbeat'
      fullPath: '/api/v1/license/heartbeat'
      preLoaderRoute: typeof ApiV1LicenseHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/license/health': {
      id: '/api/v1/license/health'
      path: '/api/v1/license/health'
      fullPath: '/api/v1/license/health'
      preLoaderRoute: typeof ApiV1LicenseHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/license/connect': {
      id: '/api/v1/license/connect'
      path: '/api/v1/license/connect'
      fullPath: '/api/v1/license/connect'
      preLoaderRoute: typeof ApiV1LicenseConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/license/activate': {
      id: '/api/v1/license/activate'
      path: '/api/v1/license/activate'
      fullPath: '/api/v1/license/activate'
      preLoaderRoute: typeof ApiV1LicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/import/incoming': {
      id: '/api/v1/import/incoming'
      path: '/api/v1/import/incoming'
      fullPath: '/api/v1/import/incoming'
      preLoaderRoute: typeof ApiV1ImportIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/documents/$id': {
      id: '/api/v1/documents/$id'
      path: '/$id'
      fullPath: '/api/v1/documents/$id'
      preLoaderRoute: typeof ApiV1DocumentsIdRouteImport
      parentRoute: typeof ApiV1DocumentsRoute
    }
    '/api/public/hooks/webhook-dispatch': {
      id: '/api/public/hooks/webhook-dispatch'
      path: '/api/public/hooks/webhook-dispatch'
      fullPath: '/api/public/hooks/webhook-dispatch'
      preLoaderRoute: typeof ApiPublicHooksWebhookDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-webhook': {
      id: '/api/public/hooks/telegram-webhook'
      path: '/api/public/hooks/telegram-webhook'
      fullPath: '/api/public/hooks/telegram-webhook'
      preLoaderRoute: typeof ApiPublicHooksTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-poll': {
      id: '/api/public/hooks/telegram-poll'
      path: '/api/public/hooks/telegram-poll'
      fullPath: '/api/public/hooks/telegram-poll'
      preLoaderRoute: typeof ApiPublicHooksTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-dispatch': {
      id: '/api/public/hooks/telegram-dispatch'
      path: '/api/public/hooks/telegram-dispatch'
      fullPath: '/api/public/hooks/telegram-dispatch'
      preLoaderRoute: typeof ApiPublicHooksTelegramDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-tick': {
      id: '/api/public/hooks/sla-tick'
      path: '/api/public/hooks/sla-tick'
      fullPath: '/api/public/hooks/sla-tick'
      preLoaderRoute: typeof ApiPublicHooksSlaTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retention-tick': {
      id: '/api/public/hooks/retention-tick'
      path: '/api/public/hooks/retention-tick'
      fullPath: '/api/public/hooks/retention-tick'
      preLoaderRoute: typeof ApiPublicHooksRetentionTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/office-callback': {
      id: '/api/public/hooks/office-callback'
      path: '/api/public/hooks/office-callback'
      fullPath: '/api/public/hooks/office-callback'
      preLoaderRoute: typeof ApiPublicHooksOfficeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/license-sync': {
      id: '/api/public/hooks/license-sync'
      path: '/api/public/hooks/license-sync'
      fullPath: '/api/public/hooks/license-sync'
      preLoaderRoute: typeof ApiPublicHooksLicenseSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-dispatch': {
      id: '/api/public/hooks/email-dispatch'
      path: '/api/public/hooks/email-dispatch'
      fullPath: '/api/public/hooks/email-dispatch'
      preLoaderRoute: typeof ApiPublicHooksEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge/$id/edit': {
      id: '/_authenticated/knowledge/$id/edit'
      path: '/edit'
      fullPath: '/knowledge/$id/edit'
      preLoaderRoute: typeof AuthenticatedKnowledgeIdEditRouteImport
      parentRoute: typeof AuthenticatedKnowledgeIdRoute
    }
    '/_authenticated/hr/leave/schedule': {
      id: '/_authenticated/hr/leave/schedule'
      path: '/hr/leave/schedule'
      fullPath: '/hr/leave/schedule'
      preLoaderRoute: typeof AuthenticatedHrLeaveScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/leave/approvals': {
      id: '/_authenticated/hr/leave/approvals'
      path: '/hr/leave/approvals'
      fullPath: '/hr/leave/approvals'
      preLoaderRoute: typeof AuthenticatedHrLeaveApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/gantt/$id': {
      id: '/_authenticated/hr/gantt/$id'
      path: '/hr/gantt/$id'
      fullPath: '/hr/gantt/$id'
      preLoaderRoute: typeof AuthenticatedHrGanttIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/v1/tasks/$id/complete': {
      id: '/api/v1/tasks/$id/complete'
      path: '/$id/complete'
      fullPath: '/api/v1/tasks/$id/complete'
      preLoaderRoute: typeof ApiV1TasksIdCompleteRouteImport
      parentRoute: typeof ApiV1TasksRoute
    }
    '/api/v1/documents/$id/versions': {
      id: '/api/v1/documents/$id/versions'
      path: '/versions'
      fullPath: '/api/v1/documents/$id/versions'
      preLoaderRoute: typeof ApiV1DocumentsIdVersionsRouteImport
      parentRoute: typeof ApiV1DocumentsIdRoute
    }
    '/api/v1/documents/$id/status': {
      id: '/api/v1/documents/$id/status'
      path: '/status'
      fullPath: '/api/v1/documents/$id/status'
      preLoaderRoute: typeof ApiV1DocumentsIdStatusRouteImport
      parentRoute: typeof ApiV1DocumentsIdRoute
    }
  }
}

interface AuthenticatedKnowledgeIdRouteChildren {
  AuthenticatedKnowledgeIdEditRoute: typeof AuthenticatedKnowledgeIdEditRoute
}

const AuthenticatedKnowledgeIdRouteChildren: AuthenticatedKnowledgeIdRouteChildren =
  {
    AuthenticatedKnowledgeIdEditRoute: AuthenticatedKnowledgeIdEditRoute,
  }

const AuthenticatedKnowledgeIdRouteWithChildren =
  AuthenticatedKnowledgeIdRoute._addFileChildren(
    AuthenticatedKnowledgeIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNomenclatureRoute: typeof AuthenticatedNomenclatureRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSubstitutionsRoute: typeof AuthenticatedSubstitutionsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminLicenseRoute: typeof AuthenticatedAdminLicenseRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedAdminOrganizationRoute: typeof AuthenticatedAdminOrganizationRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPositionsRoute: typeof AuthenticatedAdminPositionsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedContractsDocumentIdRoute: typeof AuthenticatedContractsDocumentIdRoute
  AuthenticatedCorrespondenceIncomingRoute: typeof AuthenticatedCorrespondenceIncomingRoute
  AuthenticatedCorrespondenceOutgoingRoute: typeof AuthenticatedCorrespondenceOutgoingRoute
  AuthenticatedCounterpartiesIdRoute: typeof AuthenticatedCounterpartiesIdRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedDocumentsNewRoute: typeof AuthenticatedDocumentsNewRoute
  AuthenticatedKnowledgeIdRoute: typeof AuthenticatedKnowledgeIdRouteWithChildren
  AuthenticatedKnowledgeManageRoute: typeof AuthenticatedKnowledgeManageRoute
  AuthenticatedKnowledgeNewRoute: typeof AuthenticatedKnowledgeNewRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedReferencesCatalogRoute: typeof AuthenticatedReferencesCatalogRoute
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
  AuthenticatedWorkflowsIdRoute: typeof AuthenticatedWorkflowsIdRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedCounterpartiesIndexRoute: typeof AuthenticatedCounterpartiesIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedReferencesIndexRoute: typeof AuthenticatedReferencesIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedHrGanttIdRoute: typeof AuthenticatedHrGanttIdRoute
  AuthenticatedHrLeaveApprovalsRoute: typeof AuthenticatedHrLeaveApprovalsRoute
  AuthenticatedHrLeaveScheduleRoute: typeof AuthenticatedHrLeaveScheduleRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedHrAdminIndexRoute: typeof AuthenticatedHrAdminIndexRoute
  AuthenticatedHrDirectoryIndexRoute: typeof AuthenticatedHrDirectoryIndexRoute
  AuthenticatedHrDutyIndexRoute: typeof AuthenticatedHrDutyIndexRoute
  AuthenticatedHrGanttIndexRoute: typeof AuthenticatedHrGanttIndexRoute
  AuthenticatedHrLeaveIndexRoute: typeof AuthenticatedHrLeaveIndexRoute
  AuthenticatedHrTimesheetIndexRoute: typeof AuthenticatedHrTimesheetIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNomenclatureRoute: AuthenticatedNomenclatureRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSubstitutionsRoute: AuthenticatedSubstitutionsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminLicenseRoute: AuthenticatedAdminLicenseRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
  AuthenticatedAdminOrganizationRoute: AuthenticatedAdminOrganizationRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPositionsRoute: AuthenticatedAdminPositionsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedContractsDocumentIdRoute: AuthenticatedContractsDocumentIdRoute,
  AuthenticatedCorrespondenceIncomingRoute:
    AuthenticatedCorrespondenceIncomingRoute,
  AuthenticatedCorrespondenceOutgoingRoute:
    AuthenticatedCorrespondenceOutgoingRoute,
  AuthenticatedCounterpartiesIdRoute: AuthenticatedCounterpartiesIdRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedDocumentsNewRoute: AuthenticatedDocumentsNewRoute,
  AuthenticatedKnowledgeIdRoute: AuthenticatedKnowledgeIdRouteWithChildren,
  AuthenticatedKnowledgeManageRoute: AuthenticatedKnowledgeManageRoute,
  AuthenticatedKnowledgeNewRoute: AuthenticatedKnowledgeNewRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedReferencesCatalogRoute: AuthenticatedReferencesCatalogRoute,
  AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
  AuthenticatedWorkflowsIdRoute: AuthenticatedWorkflowsIdRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedCounterpartiesIndexRoute: AuthenticatedCounterpartiesIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedReferencesIndexRoute: AuthenticatedReferencesIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedHrGanttIdRoute: AuthenticatedHrGanttIdRoute,
  AuthenticatedHrLeaveApprovalsRoute: AuthenticatedHrLeaveApprovalsRoute,
  AuthenticatedHrLeaveScheduleRoute: AuthenticatedHrLeaveScheduleRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedHrAdminIndexRoute: AuthenticatedHrAdminIndexRoute,
  AuthenticatedHrDirectoryIndexRoute: AuthenticatedHrDirectoryIndexRoute,
  AuthenticatedHrDutyIndexRoute: AuthenticatedHrDutyIndexRoute,
  AuthenticatedHrGanttIndexRoute: AuthenticatedHrGanttIndexRoute,
  AuthenticatedHrLeaveIndexRoute: AuthenticatedHrLeaveIndexRoute,
  AuthenticatedHrTimesheetIndexRoute: AuthenticatedHrTimesheetIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface VendorRouteRouteChildren {
  VendorLicenseConsoleRoute: typeof VendorLicenseConsoleRoute
  VendorLicenseIndexRoute: typeof VendorLicenseIndexRoute
}

const VendorRouteRouteChildren: VendorRouteRouteChildren = {
  VendorLicenseConsoleRoute: VendorLicenseConsoleRoute,
  VendorLicenseIndexRoute: VendorLicenseIndexRoute,
}

const VendorRouteRouteWithChildren = VendorRouteRoute._addFileChildren(
  VendorRouteRouteChildren,
)

interface ApiHealthRouteChildren {
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthLiveRoute: ApiHealthLiveRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

interface ApiV1DocumentsIdRouteChildren {
  ApiV1DocumentsIdStatusRoute: typeof ApiV1DocumentsIdStatusRoute
  ApiV1DocumentsIdVersionsRoute: typeof ApiV1DocumentsIdVersionsRoute
}

const ApiV1DocumentsIdRouteChildren: ApiV1DocumentsIdRouteChildren = {
  ApiV1DocumentsIdStatusRoute: ApiV1DocumentsIdStatusRoute,
  ApiV1DocumentsIdVersionsRoute: ApiV1DocumentsIdVersionsRoute,
}

const ApiV1DocumentsIdRouteWithChildren =
  ApiV1DocumentsIdRoute._addFileChildren(ApiV1DocumentsIdRouteChildren)

interface ApiV1DocumentsRouteChildren {
  ApiV1DocumentsIdRoute: typeof ApiV1DocumentsIdRouteWithChildren
}

const ApiV1DocumentsRouteChildren: ApiV1DocumentsRouteChildren = {
  ApiV1DocumentsIdRoute: ApiV1DocumentsIdRouteWithChildren,
}

const ApiV1DocumentsRouteWithChildren = ApiV1DocumentsRoute._addFileChildren(
  ApiV1DocumentsRouteChildren,
)

interface ApiV1TasksRouteChildren {
  ApiV1TasksIdCompleteRoute: typeof ApiV1TasksIdCompleteRoute
}

const ApiV1TasksRouteChildren: ApiV1TasksRouteChildren = {
  ApiV1TasksIdCompleteRoute: ApiV1TasksIdCompleteRoute,
}

const ApiV1TasksRouteWithChildren = ApiV1TasksRoute._addFileChildren(
  ApiV1TasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  VendorRouteRoute: VendorRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiV1ContractsRoute: ApiV1ContractsRoute,
  ApiV1DocumentsRoute: ApiV1DocumentsRouteWithChildren,
  ApiV1TasksRoute: ApiV1TasksRouteWithChildren,
  ApiPublicHooksEmailDispatchRoute: ApiPublicHooksEmailDispatchRoute,
  ApiPublicHooksLicenseSyncRoute: ApiPublicHooksLicenseSyncRoute,
  ApiPublicHooksOfficeCallbackRoute: ApiPublicHooksOfficeCallbackRoute,
  ApiPublicHooksRetentionTickRoute: ApiPublicHooksRetentionTickRoute,
  ApiPublicHooksSlaTickRoute: ApiPublicHooksSlaTickRoute,
  ApiPublicHooksTelegramDispatchRoute: ApiPublicHooksTelegramDispatchRoute,
  ApiPublicHooksTelegramPollRoute: ApiPublicHooksTelegramPollRoute,
  ApiPublicHooksTelegramWebhookRoute: ApiPublicHooksTelegramWebhookRoute,
  ApiPublicHooksWebhookDispatchRoute: ApiPublicHooksWebhookDispatchRoute,
  ApiV1ImportIncomingRoute: ApiV1ImportIncomingRoute,
  ApiV1LicenseActivateRoute: ApiV1LicenseActivateRoute,
  ApiV1LicenseConnectRoute: ApiV1LicenseConnectRoute,
  ApiV1LicenseHealthRoute: ApiV1LicenseHealthRoute,
  ApiV1LicenseHeartbeatRoute: ApiV1LicenseHeartbeatRoute,
  ApiV1LicenseRegisterKeyRoute: ApiV1LicenseRegisterKeyRoute,
  ApiV1LicenseRevokeRoute: ApiV1LicenseRevokeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
