-- EDMS typical document templates (generated from src/lib/templates/presets/edms-typical.ts)
-- Regenerate: node scripts/generate-edms-templates-migration.mjs

-- Align HR leave package templates with document type categories for the creation form.
UPDATE public.document_templates SET category = 'application'
WHERE id = 'a1b2c3d4-e5f6-4789-a012-000000000101' AND category = 'hr';

UPDATE public.document_templates SET category = 'order'
WHERE id = 'a1b2c3d4-e5f6-4789-a012-000000000102' AND category = 'hr';

UPDATE public.document_templates SET category = 'memo'
WHERE id = 'a1b2c3d4-e5f6-4789-a012-000000000103' AND category = 'hr';

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000201', 'Входящий документ', 'Кіріс құжаты', 'incoming', 'Регистрационная карточка входящей корреспонденции', 'html', 'published', '{"title_template_ru":"Вх. № {{external_reg_number}} — {{document_subject}}","title_template_kk":"Кіріс № {{external_reg_number}} — {{document_subject}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"correspondent_name","label_ru":"Контрагент","label_kk":"Контрагент","type":"text","required":true},{"key":"external_reg_number","label_ru":"Вх. № контрагента","label_kk":"Контрагент кіріс нөмірі","type":"text","required":true},{"key":"received_date","label_ru":"Дата поступления","label_kk":"Түскен күні","type":"date","required":true},{"key":"document_subject","label_ru":"Тема","label_kk":"Тақырып","type":"text","required":true},{"key":"document_summary","label_ru":"Краткое содержание","label_kk":"Қысқаша мазмұны","type":"textarea","required":true},{"key":"executor_name","label_ru":"Исполнитель","label_kk":"Орындаушы","type":"text","required":false,"source":"author"},{"key":"executor_position","label_ru":"Должность исполнителя","label_kk":"Орындаушы лауазымы","type":"text","required":false,"source":"author"},{"key":"resolution","label_ru":"Резолюция / поручение","label_kk":"Резолюция / тапсырма","type":"textarea","required":false},{"key":"attachments","label_ru":"Приложения","label_kk":"Қосымшалар","type":"textarea","required":false}],"body_template":"{{organization_name}}\n\nВХОДЯЩИЙ ДОКУМЕНТ\n\nВх. № {{external_reg_number}} от {{correspondent_name}}\nДата поступления: {{received_date}}\n\nТема: {{document_subject}}\n\nКраткое содержание:\n{{document_summary}}\n\nИсполнитель: {{executor_name}}, {{executor_position}}\nРезолюция / поручение:\n{{resolution}}\n\nПриложение: {{attachments}}"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000101', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000202', 'Исходящее письмо', 'Шығыс хат', 'outgoing', 'Стандартное исходящее письмо контрагенту', 'html', 'published', '{"title_template_ru":"Исх. письмо: {{document_subject}}","title_template_kk":"Шығыс хат: {{document_subject}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"correspondent_name","label_ru":"Контрагент","label_kk":"Контрагент","type":"text","required":true},{"key":"correspondent_address","label_ru":"Адрес контрагента","label_kk":"Контрагент мекенжайы","type":"textarea","required":false},{"key":"correspondent_contact","label_ru":"Кому (обращение)","label_kk":"Кімге","type":"text","required":true},{"key":"document_number","label_ru":"Номер документа","label_kk":"Құжат нөмірі","type":"text","required":true,"source":"system"},{"key":"document_date","label_ru":"Дата документа","label_kk":"Құжат күні","type":"date","required":true,"source":"system"},{"key":"document_subject","label_ru":"Тема","label_kk":"Тақырып","type":"text","required":true},{"key":"document_body","label_ru":"Текст","label_kk":"Мәтін","type":"textarea","required":true},{"key":"signer_position","label_ru":"Должность подписанта","label_kk":"Қол қоюшы лауазымы","type":"text","required":true,"source":"signatory"},{"key":"signer_name","label_ru":"ФИО подписанта","label_kk":"Қол қоюшы аты-жөні","type":"text","required":true,"source":"signatory"},{"key":"executor_name","label_ru":"Исполнитель","label_kk":"Орындаушы","type":"text","required":false,"source":"author"},{"key":"executor_phone","label_ru":"Телефон исполнителя","label_kk":"Орындаушы телефоны","type":"text","required":false,"source":"author"},{"key":"attachments","label_ru":"Приложения","label_kk":"Қосымшалар","type":"textarea","required":false}],"body_template":"{{organization_name}}\n\n{{correspondent_name}}\n{{correspondent_address}}\n\nИсх. № {{document_number}}\nот {{document_date}}\n\n{{document_subject}}\n\nУважаемый(ая) {{correspondent_contact}}!\n\n{{document_body}}\n\nПриложение: {{attachments}}\n\nС уважением,\n{{signer_position}}\n_______________ /{{signer_name}}/\n\nИсп.: {{executor_name}}, тел. {{executor_phone}}"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000102', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000203', 'Внутренний документ', 'Ішкі құжат', 'internal', 'Распоряжение или внутренняя служебная записка без адресата', 'html', 'published', '{"title_template_ru":"Внутренний: {{document_subject}}","title_template_kk":"Ішкі: {{document_subject}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"document_number","label_ru":"Номер документа","label_kk":"Құжат нөмірі","type":"text","required":true,"source":"system"},{"key":"document_date","label_ru":"Дата документа","label_kk":"Құжат күні","type":"date","required":true,"source":"system"},{"key":"document_subject","label_ru":"Тема","label_kk":"Тақырып","type":"text","required":true},{"key":"document_body","label_ru":"Текст","label_kk":"Мәтін","type":"textarea","required":true},{"key":"signer_position","label_ru":"Должность подписанта","label_kk":"Қол қоюшы лауазымы","type":"text","required":true,"source":"signatory"},{"key":"signer_name","label_ru":"ФИО подписанта","label_kk":"Қол қоюшы аты-жөні","type":"text","required":true,"source":"signatory"}],"body_template":"{{organization_name}}\n\nВНУТРЕННИЙ ДОКУМЕНТ\n\n№ {{document_number}}\nот {{document_date}}\n\n{{document_subject}}\n\n{{document_body}}\n\n{{signer_position}}                    _______________ /{{signer_name}}/"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000103', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000204', 'Приказ', 'Бұйрық', 'order', 'Организационно-распорядительный приказ', 'html', 'published', '{"title_template_ru":"Приказ № {{document_number}} — {{order_subject}}","title_template_kk":"Бұйрық № {{document_number}} — {{order_subject}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"document_number","label_ru":"Номер документа","label_kk":"Құжат нөмірі","type":"text","required":true,"source":"system"},{"key":"document_date","label_ru":"Дата документа","label_kk":"Құжат күні","type":"date","required":true,"source":"system"},{"key":"order_city","label_ru":"Место издания","label_kk":"Шығарылған жері","type":"text","required":false},{"key":"order_subject","label_ru":"Заголовок приказа","label_kk":"Бұйрық тақырыбы","type":"text","required":true},{"key":"order_preamble","label_ru":"Преамбула","label_kk":"Кіріспе","type":"textarea","required":false},{"key":"order_items","label_ru":"Пункты приказа","label_kk":"Бұйрық тармақтары","type":"textarea","required":true},{"key":"control_person","label_ru":"Контроль исполнения","label_kk":"Бақылау","type":"text","required":true},{"key":"signer_position","label_ru":"Должность подписанта","label_kk":"Қол қоюшы лауазымы","type":"text","required":true,"source":"signatory"},{"key":"signer_name","label_ru":"ФИО подписанта","label_kk":"Қол қоюшы аты-жөні","type":"text","required":true,"source":"signatory"}],"body_template":"{{organization_name}}\n\nПРИКАЗ № {{document_number}}\n\n{{document_date}}\n{{order_city}}\n\n{{order_subject}}\n\n{{order_preamble}}\n\nПРИКАЗЫВАЮ:\n{{order_items}}\n\nКонтроль за исполнением оставить за {{control_person}}.\n\n{{signer_position}}                    _______________ /{{signer_name}}/"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000104', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000205', 'Договор', 'Шарт', 'contract', 'Типовой договор с контрагентом', 'html', 'published', '{"title_template_ru":"Договор № {{contract_number}} — {{correspondent_name}}","title_template_kk":"Шарт № {{contract_number}} — {{correspondent_name}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"contract_number","label_ru":"Номер договора","label_kk":"Шарт нөмірі","type":"text","required":true},{"key":"contract_date","label_ru":"Дата договора","label_kk":"Шарт күні","type":"date","required":true},{"key":"contract_city","label_ru":"Место заключения","label_kk":"Жасалған жері","type":"text","required":false},{"key":"correspondent_name","label_ru":"Контрагент","label_kk":"Контрагент","type":"text","required":true},{"key":"correspondent_representative","label_ru":"Представитель контрагента","label_kk":"Контрагент өкілі","type":"text","required":true},{"key":"contract_subject","label_ru":"Предмет договора","label_kk":"Шарт пәні","type":"textarea","required":true},{"key":"contract_amount","label_ru":"Сумма","label_kk":"Сома","type":"text","required":true},{"key":"contract_term","label_ru":"Срок действия","label_kk":"Мерзімі","type":"text","required":true},{"key":"contract_body","label_ru":"Условия","label_kk":"Шарттар","type":"textarea","required":true},{"key":"contract_closing","label_ru":"Заключительные положения","label_kk":"Қорытынды","type":"textarea","required":false},{"key":"signer_position","label_ru":"Должность подписанта","label_kk":"Қол қоюшы лауазымы","type":"text","required":true,"source":"signatory"},{"key":"signer_name","label_ru":"ФИО подписанта","label_kk":"Қол қоюшы аты-жөні","type":"text","required":true,"source":"signatory"}],"body_template":"{{organization_name}}\n\nДОГОВОР № {{contract_number}}\n\nг. {{contract_city}}                                    {{contract_date}}\n\n{{organization_name}}, именуемое в дальнейшем «Заказчик», в лице {{signer_position}} {{signer_name}},\nс одной стороны, и {{correspondent_name}}, именуемое в дальнейшем «Исполнитель», в лице {{correspondent_representative}},\nс другой стороны, заключили настоящий договор о нижеследующем:\n\n1. ПРЕДМЕТ ДОГОВОРА\n{{contract_subject}}\n\n2. СТОИМОСТЬ И ПОРЯДОК РАСЧЁТОВ\nСумма договора: {{contract_amount}} тенге.\nСрок действия: {{contract_term}}.\n\n3. ПРАВА И ОБЯЗАННОСТИ СТОРОН\n{{contract_body}}\n\n4. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ\n{{contract_closing}}\n\nЗаказчик: _______________ /{{signer_name}}/\nИсполнитель: _______________ /{{correspondent_representative}}/"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000105', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000206', 'Служебная записка', 'Қызметтік жазба', 'memo', 'Типовая служебная записка с адресатом и блоком исполнителя', 'html', 'published', '{"fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"recipient_position","label_ru":"Должность адресата","label_kk":"Алушы лауазымы","type":"text","required":true},{"key":"recipient_name","label_ru":"ФИО адресата","label_kk":"Алушы аты-жөні","type":"text","required":true},{"key":"sender_position","label_ru":"Должность отправителя","label_kk":"Жіберуші лауазымы","type":"text","required":true,"source":"signatory"},{"key":"sender_name","label_ru":"ФИО отправителя","label_kk":"Жіберуші аты-жөні","type":"text","required":true,"source":"signatory"},{"key":"sender_short_name","label_ru":"ФИО отправителя (кратко)","label_kk":"Жіберуші (қысқа)","type":"text","required":true,"source":"signatory"},{"key":"document_number","label_ru":"Номер документа","label_kk":"Құжат нөмірі","type":"text","required":true,"source":"system"},{"key":"document_date","label_ru":"Дата документа","label_kk":"Құжат күні","type":"date","required":true,"source":"system"},{"key":"document_subject","label_ru":"Тема","label_kk":"Тақырып","type":"text","required":true},{"key":"document_body","label_ru":"Текст","label_kk":"Мәтін","type":"textarea","required":true},{"key":"request_block","label_ru":"Просьба / резолюция","label_kk":"Сұраныс","type":"textarea","required":true},{"key":"attachments","label_ru":"Приложения","label_kk":"Қосымшалар","type":"textarea","required":false},{"key":"executor_position","label_ru":"Должность исполнителя","label_kk":"Орындаушы лауазымы","type":"text","required":false,"source":"author"},{"key":"executor_name","label_ru":"Исполнитель","label_kk":"Орындаушы","type":"text","required":false,"source":"author"},{"key":"executor_phone","label_ru":"Телефон исполнителя","label_kk":"Орындаушы телефоны","type":"text","required":false,"source":"author"}],"body_template":"Директору {{organization_name}}\n{{recipient_position}}\n{{recipient_name}}\n\nОт {{sender_position}}\n{{sender_name}}\n\n                         СЛУЖЕБНАЯ ЗАПИСКА\n\n№ {{document_number}}\nот {{document_date}}\n\nТема: {{document_subject}}\n\n{{document_body}}\n\nВ связи с вышеизложенным прошу:\n\n{{request_block}}\n\nПриложение:\n{{attachments}}\n\n{{sender_position}}                    _____________ /{{sender_short_name}}/\n\nИсполнитель:\n{{executor_position}}\n{{executor_name}}\nтел. {{executor_phone}}","title_template_ru":"Служебная записка: {{document_subject}}","title_template_kk":"Қызметтік жазба: {{document_subject}}"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000106', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000207', 'Протокол совещания', 'Кеңес хаттамасы', 'protocol', 'Протокол заседания / совещания', 'html', 'published', '{"title_template_ru":"Протокол № {{protocol_number}} — {{document_subject}}","title_template_kk":"Хаттама № {{protocol_number}} — {{document_subject}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"protocol_number","label_ru":"Номер протокола","label_kk":"Хаттама нөмірі","type":"text","required":true},{"key":"protocol_date","label_ru":"Дата","label_kk":"Күні","type":"date","required":true},{"key":"document_subject","label_ru":"Тема","label_kk":"Тақырып","type":"text","required":true},{"key":"meeting_chair","label_ru":"Председатель","label_kk":"Төраға","type":"text","required":true},{"key":"meeting_secretary","label_ru":"Секретарь","label_kk":"Хатшы","type":"text","required":true},{"key":"participants","label_ru":"Участники","label_kk":"Қатысушылар","type":"textarea","required":true},{"key":"agenda","label_ru":"Повестка дня","label_kk":"Күн тәртібі","type":"textarea","required":true},{"key":"discussion","label_ru":"Слушали","label_kk":"Тыңдалды","type":"textarea","required":false},{"key":"decisions","label_ru":"Постановили","label_kk":"Қаулы етілді","type":"textarea","required":true}],"body_template":"{{organization_name}}\n\nПРОТОКОЛ № {{protocol_number}}\n\n{{protocol_date}}\n\nПредседатель: {{meeting_chair}}\nСекретарь: {{meeting_secretary}}\n\nПрисутствовали:\n{{participants}}\n\nПОВЕСТКА ДНЯ:\n{{agenda}}\n\nСЛУШАЛИ:\n{{discussion}}\n\nПОСТАНОВИЛИ:\n{{decisions}}\n\nПредседатель _______________ /{{meeting_chair}}/\nСекретарь _______________ /{{meeting_secretary}}/"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000107', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000208', 'Акт', 'Акт', 'act', 'Акт выполненных работ / приёмки-передачи', 'html', 'published', '{"title_template_ru":"Акт № {{act_number}} — {{act_subject}}","title_template_kk":"Акт № {{act_number}} — {{act_subject}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"act_number","label_ru":"Номер акта","label_kk":"Акт нөмірі","type":"text","required":true},{"key":"act_date","label_ru":"Дата","label_kk":"Күні","type":"date","required":true},{"key":"act_subject","label_ru":"Предмет акта","label_kk":"Акт пәні","type":"text","required":true},{"key":"act_basis","label_ru":"Основание","label_kk":"Негіз","type":"text","required":true},{"key":"correspondent_name","label_ru":"Контрагент","label_kk":"Контрагент","type":"text","required":true},{"key":"party_a","label_ru":"Представитель заказчика","label_kk":"Тапсырыс беруші","type":"text","required":true},{"key":"party_b","label_ru":"Представитель исполнителя","label_kk":"Орындаушы","type":"text","required":true},{"key":"act_body","label_ru":"Содержание акта","label_kk":"Акт мазмұны","type":"textarea","required":true}],"body_template":"{{organization_name}}\n\nАКТ № {{act_number}}\n\n{{act_date}}\n\n{{act_subject}}\n\nОснование: {{act_basis}}\n\n{{organization_name}} ({{party_a}}) и {{correspondent_name}} ({{party_b}}) составили настоящий акт о нижеследующем:\n\n{{act_body}}\n\nСтороны претензий друг к другу не имеют.\n\nОт Заказчика: _______________ /{{party_a}}/\nОт Исполнителя: _______________ /{{party_b}}/"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000108', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000209', 'Заявление', 'Өтініш', 'application', 'Общее заявление сотрудника (не отпуск — для отпуска есть отдельный шаблон)', 'html', 'published', '{"title_template_ru":"Заявление: {{application_subject}} — {{full_name}}","title_template_kk":"Өтініш: {{application_subject}} — {{full_name}}","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"full_name","label_ru":"ФИО","label_kk":"Аты-жөні","type":"text","required":true,"source":"author"},{"key":"position","label_ru":"Должность","label_kk":"Лауазым","type":"text","required":true,"source":"author"},{"key":"department","label_ru":"Подразделение","label_kk":"Бөлім","type":"text","required":true,"source":"author"},{"key":"document_date","label_ru":"Дата документа","label_kk":"Құжат күні","type":"date","required":true,"source":"system"},{"key":"application_subject","label_ru":"Тема заявления","label_kk":"Өтініш тақырыбы","type":"text","required":true},{"key":"application_body","label_ru":"Текст заявления","label_kk":"Өтініш мәтіні","type":"textarea","required":true}],"body_template":"{{organization_name}}\n\nЗАЯВЛЕНИЕ\n\nот {{full_name}}\n{{position}}, {{department}}\n\n{{document_date}}\n\n{{application_subject}}\n\n{{application_body}}\n\n\n{{full_name}}                    _______________"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000109', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

INSERT INTO public.document_templates (id, name_ru, name_kk, category, description, file_format, status, schema, default_workflow_id, allow_custom_route) VALUES ('c1b2c3d4-e5f6-4789-a012-000000000210', 'Отчёт', 'Есеп', 'report', 'Служебный отчёт за период', 'html', 'published', '{"title_template_ru":"Отчёт: {{report_subject}} ({{report_period}})","title_template_kk":"Есеп: {{report_subject}} ({{report_period}})","fields":[{"key":"organization_name","label_ru":"Организация","label_kk":"Ұйым","type":"text","required":true,"source":"organization"},{"key":"report_period","label_ru":"Отчётный период","label_kk":"Есеп кезеңі","type":"text","required":true},{"key":"report_subject","label_ru":"Тема отчёта","label_kk":"Есеп тақырыбы","type":"text","required":true},{"key":"report_summary","label_ru":"Краткие выводы","label_kk":"Қысқаша қорытынды","type":"textarea","required":true},{"key":"report_body","label_ru":"Содержание отчёта","label_kk":"Есеп мазмұны","type":"textarea","required":true},{"key":"author_name","label_ru":"Составитель","label_kk":"Дайындаушы","type":"text","required":true,"source":"author"},{"key":"author_position","label_ru":"Должность составителя","label_kk":"Дайындаушы лауазымы","type":"text","required":true,"source":"author"}],"body_template":"{{organization_name}}\n\nОТЧЁТ\n\nза период: {{report_period}}\n\nТема: {{report_subject}}\n\nКраткие выводы:\n{{report_summary}}\n\n{{report_body}}\n\n{{author_position}}                    _______________ /{{author_name}}/"}'::jsonb, 'b1b2c3d4-e5f6-4789-a012-000000000110', true)
ON CONFLICT (id) DO UPDATE SET
  name_ru = EXCLUDED.name_ru,
  name_kk = EXCLUDED.name_kk,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  status = EXCLUDED.status,
  schema = EXCLUDED.schema,
  default_workflow_id = EXCLUDED.default_workflow_id,
  allow_custom_route = EXCLUDED.allow_custom_route;

